name: Build e Analise SonarCloud (Go)

on:
  push:
    branches:
      - main
      - sprint2
      - sprint3
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - sprint2
      - sprint3

jobs:
  sonarcloud:
    name: Build e Analise
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para o SonarCloud analisar o histórico de commits
      
      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Ajuste para a versão que você usa no projeto

      - name: Rodar Testes e Gerar Cobertura
        run: |
          cd API-5SEM-BACKEND
          go test -v -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=DenariusData_API-5SEM-BACKEND
            -Dsonar.organization=denarius
            -Dsonar.go.coverage.reportPaths=API-5SEM-BACKEND/coverage.out
            -Dsonar.projectBaseDir=API-5SEM-BACKEND
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go