name: Analise SonarCloud

on:
  push:
    branches: [main, sprint2, sprint3]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Rodar Testes e Gerar Cobertura
        run: |
          go test -v -coverprofile=./coverage.out ./...
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=DenariusData_API-5SEM-BACKEND
            -Dsonar.organization=denariusdata
            -Dsonar.go.coverage.reportPaths=coverage.out